apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-app
  labels:
    app: team-a-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-a-app
  template:
    metadata:
      labels:
        app: team-a-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
